Dev
mihkos/udp_generator_listener pull request #2
Opened 2019-04-04 21:39 UTC by mihkos

1).h --> .hpp
2) add #pragma once
3) add runtime_error()
4) redesigned constructors, deconstructors
5) add signal for stop

2019-04-05 08:18 UTC, log0div0 requested changes

2019-04-05 08:18 UTC, log0div0 commented on CMakeLists.txt
> +FIND_PACKAGE( Boost 1.40 COMPONENTS thread REQUIRED )
зависимость от boost убираем

2019-04-05 08:18 UTC, log0div0 commented on CMakeLists.txt
> +set(HEADERS includes.hpp generator/generator.hpp listener/listener.hpp)
Заголовочные файлы не являются единицей компиляции. Компилируются только cpp файлы.

2019-04-05 08:18 UTC, log0div0 commented on generator/generator.cpp
> +        throw std::runtime_error("error create socket!");
добавляем фигурные скобочки, даже если if состоит из одной строки

2019-04-05 08:18 UTC, log0div0 commented on generator/generator.cpp
> +        throw std::runtime_error("error bind socket with address!");
Не закрывается this_socket. Если исключение бросается до завершения конструктора, то деструктор не вызовется

2019-04-05 08:18 UTC, log0div0 commented on generator/generator.cpp
> +    boost::thread sender(&UDPGenerator::handle, this);
проще лямбдой написать
```suggestion
    std::thread sender([&] {handle()});
```

2019-04-05 08:18 UTC, log0div0 commented on generator/generator.cpp
> +    std::cout << "For stopping send input \"stop\": " << std::endl;
лучше навесить обработчик на сигнал SIGINT

2019-04-05 08:18 UTC, log0div0 commented on generator/generator.cpp
> +    sender.detach();
не нужно

2019-04-05 08:18 UTC, log0div0 commented on generator/generator.cpp
> +    sender.interrupt();
не нужно

2019-04-05 08:18 UTC, log0div0 commented on generator/generator.cpp
> +    auto size_dgram = static_cast<size_t >(fillTestMessage(msg));
почему бы fillTestMessage сразу не возвращать size_t?

2019-04-05 08:18 UTC, log0div0 commented on generator/generator.hpp
> +    std::atomic<bool> t_running;
зачем делать эту переменную атомарной?

2019-04-05 08:18 UTC, log0div0 commented on listener/listener.cpp
> +        throw std::runtime_error("bind function");
не освобождается this_socket

2019-04-05 08:18 UTC, log0div0 commented on listener/listener.cpp
>      struct sockaddr_in addr;
отучайся от привычки объявлять переменные в начале функции. это Сишное требование. в С++ объявляй переменную там, где она непосредственно используется

2019-04-05 08:18 UTC, log0div0 commented on listener/listener.cpp
>      double elapsed_seconds;
ну вот, например, зачем её здесь объявлять. объяви там, где она инициализируется

2019-04-05 08:18 UTC, log0div0 commented on listener/listener.cpp
> +        elapsed_seconds = boost::chrono::duration_cast<boost::chrono::microseconds>(end-start).count() / 1000000.0;
зачем приводить к микросекундам, а потом делить на миллион? почему бы сразу не привести к секундам

2019-04-05 08:18 UTC, log0div0 commented on listener/listener.cpp
> +        bytes_read = static_cast<int>(recvfrom(this_socket, buf, 32768, 0, nullptr, nullptr));
recvfrom и так возвращает int

2019-04-05 08:18 UTC, log0div0 commented on listener/listener.hpp
> +    std::atomic<bool> t_running;
не нужен atomic

2019-04-05 08:18 UTC, log0div0 commented on main.cpp
> +            auto listener = new UDPListener(current_params.sport);
зачем new? память выделяешь, а потом не освобождаешь. нехорошо это. лучше вообще без new, он тут не нужен

2019-04-05 08:18 UTC, log0div0 commented on main.cpp
> +        std::cerr << "Caught: " << error.what( ) << std::endl;
`return 1;`

2019-04-05 19:42 UTC, mihkos commented on CMakeLists.txt
> +FIND_PACKAGE( Boost 1.40 COMPONENTS thread REQUIRED )
boost совсем не в почете?

2019-04-08 20:56 UTC, CIDJEY commented on CMakeLists.txt
> +set(CMAKE_REQUIRED_FLAGS -std=c++17)
Wall лучше вернуть, предупреждения бывают очень полезными

2019-04-08 21:05 UTC, CIDJEY commented on generator/generator.cpp
> +void UDPGenerator::setDestAddr(std::string dest_ip, unsigned short dport) {
когда предполагается, что параметр-объект класса не будет изменяться внутри функции или метода, то лучше передавать его по константной ссылке, избежав таким образом лишнего копирования

2019-04-08 21:07 UTC, CIDJEY commented on generator/generator.cpp
> +UDPGenerator::UDPGenerator() : UDPGenerator(0){}
У тебя нигде не создается UDPGenerator с конструктором по умолчанию. В таких случаях лучше явно запретить использование конструктора по умолчанию UDPGenerator() = delete;

2019-04-08 21:09 UTC, CIDJEY commented on generator/generator.cpp
> +UDPGenerator::UDPGenerator(unsigned short sport) {
Почему нельзя просто передать сюда целиком params и сразу вытащить все нужные поля? Зачем двухэтапная инициализация вместе с setDestAddr?

2019-04-08 21:10 UTC, CIDJEY commented on generator/generator.cpp
> +    std::thread sender([&] {handle();});
Серега тебе рекомендовал делать лямбду как раз чтобы можно было вообще избавиться от метода handle. Просто прям пиши код от handle в саму лямбду

2019-04-08 21:14 UTC, CIDJEY commented on generator/generator.cpp
> +    return static_cast<size_t >(counter);
Зачем вся эта свестопляска с преобразованием типов? Тебе же уже вернулся size_t, зачем ты его туда-сюда гоняешь? Работай прям с ним. К тому же, static_cast далеко не лучший кандидат на выполнение таких преобразований типов. Если уж хочется что-то куда-то конвертировать, то достаточно просто использовать скобочки

2019-04-08 21:16 UTC, CIDJEY commented on main.cpp
> +namespace globalarea {
не нужно воротить целое пространство имен только ради одной переменной

2019-04-08 21:32 UTC, CIDJEY commented on listener/listener.cpp
> +UDPListener::UDPListener(unsigned short listen_port) {
см. генератор

2019-04-08 21:34 UTC, CIDJEY commented on listener/listener.cpp
> +void UDPListener::startListener() {
Название метода не очень удачное. В названии класса уже указано, что это Listener. Не нужно дублировать это в названии метода. Достаточно просто start.

2019-04-08 21:35 UTC, CIDJEY commented on listener/listener.cpp
>  void UDPListener::calculatingSpeed(std::atomic<long>* received_bytes) {
Название метода обычно отражает некоторое действие. Поэтому лучше calculateSpeed

2019-04-08 21:41 UTC, CIDJEY commented on listener/listener.cpp
> +        int bytes_read = recvfrom(this_socket, buf, 32768, 0, nullptr, nullptr);
UDP_LENGTH_DATAGRAM (с одной M на конце, кстати)

2019-04-12 16:42 UTC, CIDJEY commented on listener/listener.cpp
> +    std::thread receiver([&] () mutable {
mutable не нужен

2019-04-12 20:56 UTC, merged