added tcp listener and generator, added cmake build type: release and…
mihkos/udp_generator_listener pull request #3
Opened 2019-04-15 22:13 UTC by mihkos

… debug

2019-04-17 11:22 UTC, CIDJEY commented on generator/generator.cpp
> +            buf[bytes_read] = '\0';
Зачем проставлять терминирующий ноль? Мы же не печатаем ничего на экран

2019-04-17 11:27 UTC, CIDJEY commented on listener/listener.cpp
> +TCPListener::TCPListener(const params& current_params) : Listener(current_params) {
Такие короткие методы можно писать прям в заголовочнике

2019-04-17 11:28 UTC, CIDJEY commented on listener/listener.cpp
> +UDPListener::~UDPListener() = default;
Перенести в хедер

2019-04-17 11:36 UTC, CIDJEY commented on listener/listener.cpp
> +            if(t_running) {
лишняя проверка

2019-04-17 11:37 UTC, CIDJEY commented on listener/listener.cpp
> +            } while ((errno == EAGAIN) && (t_running != 0));
Ничего страшного если флажок is_running уже выставлен, а мы в середине цикла. Можно спокойно доделать итерацию цикла, а затем на следующей итерации мы заметим, что пора заканчивать

2019-04-18 12:57 UTC, CIDJEY commented on main.cpp
> +int parseArgs(int argc, char** argv, params* current_params) {
Никогда не возвращается int. Лучше пусть функция возвращает новую структуру с настройками

2019-04-18 12:59 UTC, CIDJEY commented on listener/listener.hpp
> +//#include "../includes.hpp"
коментарии убираем

2019-04-18 13:04 UTC, CIDJEY commented on listener/listener.hpp
> +        _speedmeter = std::thread([&] () {
Запуск потока лучше перетащить в start. Да, start при этом перестанет быть чисто виртуальным

2019-04-18 13:05 UTC, CIDJEY commented on listener/tcplistener.hpp
> +
Я бы не сказал, что это такая маленькая функция чтобы ее можно было безболезненно указывать в .hpp. Сделай нормальное разделение на хедеры и исходники

2019-04-18 20:11 UTC, log0div0 requested changes

2019-04-18 20:11 UTC, log0div0 commented on socket.hpp
> +            if(setsockopt(_this_socket, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv)) < 0) {
а для tcp мы почему это не делаем?

2019-04-18 20:11 UTC, log0div0 commented on socket.hpp
> +        if (bind(_this_socket, (sockaddr *) &addr, sizeof(addr)) < 0) {
Лучше этот кусок кода выделить в отдельный метод и вызывать снаружи класса

2019-04-18 20:11 UTC, log0div0 commented on generator/tcpgenerator.hpp
> +        std::thread sender([&] () {
В udp генераторе два потока - sender и receiver. А тут только один.

2019-04-18 20:11 UTC, log0div0 commented on generator/generator.hpp
> +        size_t counter = 0;
Зачем тебе counter, если ты можешь вместо него использовать `res_test_msg.size()`

2019-04-22 20:43 UTC, merged